# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-moje-radxa"
BBFILE_PATTERN_meta-moje-radxa = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-moje-radxa = "6"

LAYERDEPENDS_meta-moje-radxa = "core"
LAYERSERIES_COMPAT_meta-moje-radxa = "scarthgap"
