[main]
# Použít pouze keyfile plugin (ignoruje /etc/network/interfaces)
# Bez tohoto nastavení NM/ifupdown plugin označí wlan0 jako unmanaged
plugins=keyfile
no-auto-default=*

[keyfile]
path=/etc/NetworkManager/system-connections

[logging]
level=WARN
